trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: DownloadSecureFile@1
  name: keystore_properties
  inputs:
    secureFile: 'keystore.properties'

- task: DownloadSecureFile@1
  name: mathandoro_jks
  inputs:
    secureFile: 'mathandoro.jks'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cp $(keystore_properties.secureFilePath) .
      cp $(mathandoro_jks.secureFilePath) .
      gem install fastlane
      fastlane build_beta
      fastlane build_prod
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './app/build'
    ArtifactName: 'build'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: './fastlane'
    ArtifactName: 'fastlane'
    publishLocation: 'Container'
