# Android
# Build your Android project with Gradle.
# Add steps that test, sign, and distribute the APK, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/android

trigger:
- master

pool:
  vmImage: 'macos-latest'

steps:

- task: DownloadSecureFile@1
  name: keystore_properties
  inputs:
    secureFile: 'keystore.properties'

- task: DownloadSecureFile@1
  name: mathandoro_jks
  inputs:
    secureFile: 'mathandoro.jks'

- task: Bash@3
  inputs:
    targetType: 'inline'
    script: |
      cp $(keystore_properties.secureFilePath) .
      cp $(mathandoro_jks.secureFilePath) .
      gem install fastlane
      # echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
      # echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
      fastlane build_beta
      ls -alh
      # fastlane upload_beta
