# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "07f0e8b1-3beb-461c-ad37-1f65b885851a"

default_platform :android

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later

lane :build_beta do
  gradle(task: "assemble", build_type: "Release", flavor: "beta")
end

lane :upload_beta do
  supply(track: "beta", package_name: "com.mathandoro.coachplus.beta", apk: "app/build/outputs/apk/app-beta-release.apk")
  # slack(
  #   slack_url: "https://hooks.slack.com/services/IDS"
  # )
end
