name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-18.04
    
    steps:
    - uses: actions/checkout@v1
    - name: Build
      env: 
        ci_cd_secret_key: ${{ secrets.ci_cd_secret_key }}
        test: ${{ secrets.test }}
      run: |
        sudo apt-add-repository -y ppa:rael-gc/rvm
        sudo apt-get update
        # install rvm
        gpg --keyserver hkp://pool.sks-keyservers.net --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3 7D2BAF1CF37B13E2069D6956105BD0E739499BDB
        rm -rf ~/.rvm
        curl -L https://get.rvm.io | bash -s stable
        source /home/runner/.rvm/scripts/rvm
        # sudo apt-get install -y ruby
        gpg --quiet --batch --yes --decrypt --passphrase="$ci_cd_secret_key" --output secrets.tar secrets.tar.gpg
        tar xvf secrets.tar
        rvm install 2.1
        gem install fastlane
        # echo y | android update sdk --no-ui --all --filter "tool,extra-android-m2repository,extra-android-support,extra-google-google_play_services,extra-google-m2repository"
        # echo y | $ANDROID_HOME/tools/bin/sdkmanager "extras;m2repository;com;android;support;constraint;constraint-layout-solver;1.0.2"
    - name: Publish
      run: fastlane build_beta

